###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "teste23",
    "email": "teste2233@user.com",
    "password": "admin",
    "role": "READER"
}

###
GET http://localhost:3000/users
###
GET http://localhost:3000/users/cmc0t8gig000018z6egzcne6f

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "teste@user.com",
    "password": "admin" 
}